### ISSUE TITLE
Fails to open valid tiff (OS X)

### ISSUE THREAD

**Issue by qu1j0t3** [brouhaha/tumble#9]
I get the following error with a valid TIFF file: `TekInstructionManual_515_515A_P31.tif: Not a TIFF or MDI file, bad magic number 57125 (0xdf25).`

```
$ tumble -v TekInstructionManual_515_515A_P31.tif -o TekInstructionManual_515_515A_P31.pdf
TekInstructionManual_515_515A_P31.tif: Not a TIFF or MDI file, bad magic number 57125 (0xdf25).
can't open input file 'TekInstructionManual_515_515A_P31.tif'
unrecognized format for input file 'TekInstructionManual_515_515A_P31.tif'
fatal error: error opening input file "TekInstructionManual_515_515A_P31.tif"

$ tiffinfo TekInstructionManual_515_515A_P31.tif
TIFF Directory at offset 0x81292 (13d8c)
  Image Width: 3420 Image Length: 4416
  Resolution: 400, 400 pixels/inch
  Bits/Sample: 1
  Sample Format: unsigned integer
  Compression Scheme: LZW
  Photometric Interpretation: min-is-white
...
$ hexdump -C TekInstructionManual_515_515A_P31.tif |head
00000000  49 49 2a 00 8c 3d 01 00  80 3f e0 50 38 24 16 0d  |II*..=...?.P8$..|
```

This appears to be due to the magic number sniffing code in `open_tiff_input_file`; commenting out these lines allows libtiff to open the file:

```
  l = fread (& buf [0], 1, sizeof (buf), f);
  if (l != sizeof (buf))
    return (0);

  rewind (f);

  if (! (((buf [0] == 0x49) && (buf [1] == 0x49)) ||
	 ((buf [0] == 0x4d) && (buf [1] == 0x4d))))
    return (0);
```

I don't immediately see the bug here but I wonder if it would be better to let libtiff do the magic number detection?

**Comment by brouhaha** [comment]
The check is because tumble will try to open files using every input handler, but prefers not to call an image library until the file type is identified. Possibly that code could be removed, but the idea was that if the magic wasn't there, it would return a silent failure, whereas if the magic identifies it as a TIFF file but TIFFFdOpen() fails, then there's actually something wrong with the file and the error should be reported. I'd prefer to find out why the check is failing, Perhaps putting a rewind() before the fread() might help?

At the moment it's inconvenient for me to test on MacOS.

**Comment by qu1j0t3** [comment]
It's been a while but istr that I tried `rewind()` and it did not fix it.

**Comment by brouhaha** [comment]
Possibly the same issue as #2, so hopefully fixed now by also using lseek(). If it's still broken, you can reopen this, or open a new issue.
